# Generated by Django 4.2.2 on 2024-01-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clusterdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=255)),
                ('cluster_name', models.CharField(default='', max_length=255)),
                ('clust_data', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Nodedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=255)),
                ('node_name', models.CharField(default='', max_length=255)),
                ('Loc_lat', models.CharField(default='', max_length=20)),
                ('Loc_long', models.CharField(default='', max_length=20)),
                ('api_key', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodename', models.CharField(max_length=255)),
                ('depth_1', models.FloatField(default=0.0)),
                ('depth_2', models.FloatField(default=0.0)),
                ('depth_3', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
